theme: jekyll-theme-minimal
title: David Immanuel Maksi
future: true
description: |
  Welcome to My Page. 
  Kindly view my sample project portfolio here: 
  1. https://github.com/DavidIMk/WideWorldImporters 
  2. https://github.com/DavidIMk/ShoppingCart<br/>
