theme: jekyll-theme-minimal
title: David Immanuel Maksi
description: Welcome to my page.<br/>
Kindly view my sample project portfolio here:<br/>
1. https://github.com/DavidIMk/WideWorldImporters<br/>
2. https://github.com/DavidIMk/ShoppingCart<br/>
